name: Matt Preston Music
favicon: null
layout_spectrum: 0.24828
typography_spectrum: 0.5613568013068289
title: Matt Preston Music
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#575c56'
    - '#d7dcd6'
    - '#969696'
    - '#f7fcf6'
  brandStrength: 0
  lightness: 0.04582339967601001
  saturation: 0.5395146603696048
  rhythmicContrast: 0.0512674490455538
purpose: []
